run:
  timeout: 15m
  tests: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - mnd
    - gocyclo
    - revive
    - gosimple
    - goconst
    - misspell
    - unconvert
    - unused
    - ineffassign
    - gocritic
    - staticcheck
    - gosec
    - errcheck
    - goimports
    - typecheck
    - govet
    - gofmt
    - whitespace
    - gofumpt
    - dupl
    - wsl
    - lll
    - ireturn
    - gci
    - forbidigo

linters-settings:
  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      - generic
      - git.time2go.tech/antifraud/frogocore/queue/nats.Pool
      - git.time2go.tech/antifraud/frogocore/db/aerospike.Namespace
      - git.time2go.tech/antifraud/frogocore/fastlog/metrics.Chart
      - git.time2go.tech/antifraud/frogocore/db/mongodb.Client
      - git.time2go.tech/antifraud/frogocore/queue/nats/client.Logger
      - git.time2go.tech/antifraud/frogocore/utils/phone.Decoder
      - git.time2go.tech/antifraud/frogocore/queue/nats/consumer.Client
      - github.com/neo4j/neo4j-go-driver/v5/neo4j/auth.TokenManager
      - github.com/aerospike/aerospike-client-go/v7.Error
      - github.com/aerospike/aerospike-client-go/v7.Value
      - gorgonia.org/gorgonia.Value
      - go.opentelemetry.io/otel/trace.Span
      - go.opentelemetry.io/otel/metric.Meter
      - github.com/nats-io/nats.go.JetStreamContext
      - golang.org/x/text/transform.Transformer
  lll:
    line-length: 120
    tab-width: 1
  wsl:
    strict-append: false
    allow-assign-and-call: true
    allow-assign-and-anything: true
    allow-multiline-assign: true
    force-case-trailing-whitespace: 0
    allow-trailing-comment: true
    allow-separated-leading-comment: true
    allow-cuddle-declarations: true
    allow-cuddle-with-calls: ["Lock", "RLock"]
    allow-cuddle-with-rhs: ["Unlock", "RUnlock"]
    force-err-cuddling: false
    error-variable-names: ["err"]
    force-short-decl-cuddling: false
  gci:
    sections:
      - standard
      - blank
      - dot
      - default
      - prefix(git.time2go.tech/antifraud/frogocore)
    custom-order: true
  forbidigo:
    forbid:
      - ^print.*$
      - pkg: "github.com/golang/mock/gomock"
      - p: ^fmt\.Print.*$
        msg: Do not commit print statements.
      - ^log\.Print.*$
    exclude-godoc-examples: false
    analyze-types: true

issues:
  exclude-rules:
    - path: utils/strings.go
      linters: [gosec]
      text: "G115: integer overflow conversion int -> uint32"
    - path: utils/strings.go
      linters: [gosec]
      text: "G115: integer overflow conversion uint64 -> int64"
    - path: dataconv/binary.go
      linters: [gosec]
      text: "G115: integer overflow conversion int -> uint32"
    - path: dataconv/binary.go
      linters: [gosec]
      text: "G115: integer overflow conversion int -> uint16"
    - path: dataconv/binary.go
      linters: [gosec]
      text: "G115: integer overflow conversion uint32 -> int32"
    - path: dataconv/binary.go
      linters: [gosec]
      text: "G115: integer overflow conversion uint64 -> int64"
    - path: dataconv/binary.go
      linters: [gosec]
      text: "G115: integer overflow conversion uint16 -> int16"
    - path: memory/sortedset/sortedset.go
      linters: [gosec]
      text: "G115: integer overflow conversion uint64 -> int"
    - path: queue/nats/proxy/balancer.go
      linters: [gosec]
      text: "G115: integer overflow conversion int -> uint32"
    - path: db/aerospike/aerospike.go
      linters: [gosec]
      text: "G115: integer overflow conversion uint64 -> int64"
    - path: memory/fuzzysearch/fuzzy_test.go
      linters: [forbidigo]
    - path: _test\.go
      linters:
        - mnd
        - lll
        - wsl
        - dogsled
        - errcheck
        - bodyclose
        - dupl
    - path: _easyjson\.go
      linters:
        - mnd
        - lll
        - wsl
        - dogsled
        - errcheck
        - bodyclose
        - dupl
        - typecheck
    - path: _example\.go
      linters:
        - mnd
        - dogsled
        - errcheck
        - bodyclose
    - path: _mock\.go
      linters:
        - mnd
        - dogsled
        - errcheck
        - bodyclose
        - typecheck
  new-from-rev: ""
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
