// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package proxy

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (Subscribe) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*Subscribe) UnmarshalJSON([]byte) error        { return nil }
func (Subscribe) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*Subscribe) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Subscribe *Subscribe

func (Unsubscribe) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*Unsubscribe) UnmarshalJSON([]byte) error        { return nil }
func (Unsubscribe) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*Unsubscribe) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Unsubscribe *Unsubscribe
