name: Go

on:
  push:
    branches:
      - main

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.24' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: |
          go get .
          go install github.com/jstemmer/go-junit-report@latest
          go install github.com/vladopajic/go-test-coverage/v2@latest
      - name: Test with the Go CLI
        run: |
          GOMAXPROCS=$(nproc) go test -coverprofile=coverage.out -cover -race -tags="unit integration" -p $(nproc) -parallel=$(nproc) ./...
          go-test-coverage --config=./.testcoverage.yml
          gocover-cobertura < coverage.out > coverage.xml
      - name: Bench
        run: go test -bench=. -run="^$$" ./...
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-${{ matrix.go-version }}-Test-Coverage
          path: coverage.xml